# -*- coding: utf-8 -*-
"""Assignment-8.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ip1UXNzh-x_DgbYTC8IbOMA_-xwk5bK
"""

import numpy as np
import matplotlib.pyplot as plt
 
#Generate line points
def line_gen(A,B):
  len =10
  dim = A.shape[0]
  x_AB = np.zeros((dim,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB
 
#Plotting line 2x+y = 6
A=np.array([0,6])
B=np.array([3,0])
AB=line_gen(A,B)
plt.plot(AB[0,:],AB[1,:],label='2x+y=6')
 
#Plotting line 3x+4y=12
P=np.array([0,3])
Q=np.array([4,0])
PQ=line_gen(P,Q)
plt.plot(PQ[0,:],PQ[1,:],label='3x+4y=12')
 
#Shading Required Region
x1=[0,12/5,3]
y1=[3,6/5,0]
plt.fill(x1,y1,color='green',alpha=0.3)
 
#Labelling points
plt.plot(0,3,'o',color='r')
plt.text(0.2,3.5,'A(0,3)')
plt.plot(12/5,6/5,'o',color='r')
plt.text(2.4,1.2,'B(12/5,6/5)')
plt.plot(3,0,'o',color='r')
plt.text(3.2,0.2,'C(3,0)')
 
plt.xlabel('x')
plt.ylabel('y')
plt.legend(loc='best')
plt.grid() # minor
plt.axis('equal')
plt.show()